Streamline ADC data collection
K3Engineering/dynamite-sampler-firmware pull request #18
Opened 2024-12-12 23:48 UTC by dl-dl

2024-12-17 00:06 UTC, larryk3 requested changes
toSend data does not get copied over properly

2024-12-17 00:06 UTC, larryk3 commented on main/main.cpp
> +	xStreamBufferSend(adcStreamBufferHandle, &toSend, sizeof(toSend), 0);
```suggestion
	memcpy(toSend.data, adcReading.data, sizeof(toSend.data));
	xStreamBufferSend(adcStreamBufferHandle, &toSend, sizeof(toSend), 0);
```

2024-12-17 16:27 UTC, larryk3 requested changes

2024-12-17 20:11 UTC, dl-dl commented on main/main.cpp
> +struct BlePublAdcData {
Ok. Done.

2024-12-17 20:15 UTC, dl-dl commented on main/main.cpp
> +	esp_pm_config_t pmConfig = {
Probably by mistake. Reinstated.

2024-12-17 20:23 UTC, dl-dl commented on main/main.cpp
> +	memcpy(toSend.data, adcReading.data, sizeof(toSend.data));
Let's return to it later, when we know what exactly we need to send.

2024-12-17 21:12 UTC, dl-dl commented on main/main.cpp
> +constexpr size_t ADC_STREAM_TRIGGER =
or ADC_BLE_FEED_CHUNK

2024-12-17 22:04 UTC, vladkvit commented on main/ADS131M0x.cpp
> +// #include "Arduino.h"
Consider removing the comment

2024-12-17 23:20 UTC, larryk3 commented on main/main.cpp
> +constexpr size_t ADC_STREAM_TRIGGER =
`ADC_FEED_CHUNK`
```
// To increase throughput, ADC data is grouped and sent as a chunk of multiple readings.
// Send the maximum amount of adc readings that can fit in a BLE payload.
```

2024-12-17 23:25 UTC, dl-dl commented on main/main.cpp
> +constexpr size_t ADC_STREAM_TRIGGER =
Done.

2024-12-17 23:26 UTC, dl-dl commented on main/ADS131M0x.cpp
> +// #include "Arduino.h"
No.

2024-12-18 17:16 UTC, larryk3 approved these changes

2024-12-18 17:18 UTC, merged