Divide main.cpp
K3Engineering/dynamite-sampler-firmware pull request #19
Opened 2024-12-19 12:44 UTC by dl-dl

2024-12-19 23:06 UTC, larryk3 requested changes
I locally tested the suggested changes, and it seems to work. But need to do more testing.

2024-12-20 01:27 UTC, dl-dl commented on main/main.cpp
> +	Serial.println("temprary out of order\n");
I did not know what to include to make it compile.

2024-12-20 01:34 UTC, larryk3 commented on main/main.cpp
> +	Serial.println("temprary out of order\n");
I think its arduino. The same function is called in the `ble_proc.cpp` file.
We can probably just call the underlying function directly and not depend on arduino as much.
```
uint64_t EspClass::getEfuseMac(void) {
  uint64_t _chipmacid = 0LL;
  esp_efuse_mac_get_default((uint8_t *)(&_chipmacid));
  return _chipmacid;
}
```

2024-12-20 01:40 UTC, dl-dl commented on main/ble_proc.cpp
> +}
Fixed.

2024-12-20 01:54 UTC, dl-dl reviewed
OK. Committed.

2024-12-20 15:29 UTC, larryk3 approved these changes

2024-12-20 15:32 UTC, merged